version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: walletprofile-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: walletprofile
      RABBITMQ_DEFAULT_PASS: walletpro
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data: